name: React CI with Vite

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 원하는 Node.js 버전으로 변경
      
      - name: Build and Run Docker on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Pull latest code from dev branch
            cd /home/ubuntu/react
            git pull origin dev

            # Create .env file
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
            echo "VITE_SPOTIFY_CLIENT_ID=${{ secrets.VITE_SPOTIFY_CLIENT_ID }}" >> .env
            echo "VITE_SPOTIFY_REDIRECT_URI=${{ secrets.VITE_SPOTIFY_REDIRECT_URI }}" >> .env
            echo "VITE_SPOTIFY_CLIENT_SECRET=${{ secrets.VITE_SPOTIFY_CLIENT_SECRET }}" >> .env
            echo "VITE_KAKAO_CLIENT_ID=${{ secrets.VITE_KAKAO_CLIENT_ID }}" >> .env
            echo "VITE_KAKAO_REDIRECT_URI=${{ secrets.VITE_KAKAO_REDIRECT_URI }}" >> .env
            echo "VITE_APP_YOUTUBE_API_KEY=${{ secrets.VITE_APP_YOUTUBE_API_KEY }}" >> .env
            echo "VITE_CHAT_API_URL=${{ secrets.VITE_CHAT_API_URL }}" >> .env
            
            # Install dependencies
            npm install
            
            # Build React app using Vite
            npm run build

            # 🛠 빌드된 파일 목록 출력 (압축 파일 확인)
            echo "🔍 Checking built files..."
            ls -lh dist/assets/
